In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv('C:/Users/PC/Documents/personal development/HAMOYE/Regression - Predicting Energy Efficiency of Buildings/QUIZ/energydata_complete (1).csv')

pd.set_option('display.max_columns',None)
df.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4       RH_4         T5   RH_5        T6  \
0  19.79  44.730000  19.000000  45.566667  17.166667  55.20  7.026667   
1  19.79  44.790000  19.000000  45.992500  17.166667  55.20  6.833333   
2  19.79  44.933333  18.926667  45.890000  17.166667  55.09  6.560000   
3  19.79  45.000000  18.890000  45.723333  17.166667  55.09  6.433333   
4  19.79  45.000000  18.890000  45.530000  17.200000  55.09  6.366667   

        RH_6         T7       RH_7    T8       RH_8         T9   RH_9  \
0  84.256667  17.200000  41.626667  18.2  48.900000  17.033333  45.53   
1  84.063333  17.200000  41.560000  18.2  48.863333  17.066667  45.56   
2  83.156667  17.200000  41.433333  18.2  48.730000  17.000000  45.50   
3  83.423333  17.133333  41.290000  18.1  48.590000  17.000000  45.40   
4  84.893333  17.200000  41.230000  18.1  48.590000  17.000000  45.40   

      T_out  Press_mm_hg  RH_out  Windspeed  Visibility  Tdewpoint        rv1  \
0  6.600000        733.5    92.0   7.000000   63.000000        5.3  13.275433   
1  6.483333        733.6    92.0   6.666667   59.166667        5.2  18.606195   
2  6.366667        733.7    92.0   6.333333   55.333333        5.1  28.642668   
3  6.250000        733.8    92.0   6.000000   51.500000        5.0  45.410389   
4  6.133333        733.9    92.0   5.666667   47.666667        4.9  10.084097   

         rv2  
0  13.275433  
1  18.606195  
2  28.642668  
3  45.410389  
4  10.084097

In [23]:
x = df[['T2']]
y = df['T6']
y

0         7.026667
1         6.833333
2         6.560000
3         6.433333
4         6.366667
           ...    
19730    24.796667
19731    24.196667
19732    23.626667
19733    22.433333
19734    21.026667
Name: T6, Length: 19735, dtype: float64

In [24]:
x

T2
0      19.200000
1      19.200000
2      19.200000
3      19.200000
4      19.200000
...          ...
19730  25.890000
19731  25.754000
19732  25.628571
19733  25.414000
19734  25.264286

[19735 rows x 1 columns]

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [27]:
from sklearn.linear_model import LinearRegression

In [28]:
df_lreg = LinearRegression()

In [29]:
x_train
#y_train

T2
11553  20.566667
6580   18.426667
4130   20.633333
9812   20.100000
18178  21.434000
...          ...
11284  19.390000
11964  22.000000
5390   18.200000
860    20.434000
15795  19.890000

[13222 rows x 1 columns]

In [30]:
df_lreg.fit(x_train,y_train)

LinearRegression()

In [32]:
prediction = df_lreg.predict(x_test)

In [33]:
from sklearn.metrics import r2_score

In [34]:
r2_score(y_test,prediction)

0.64401394660513

In [36]:
df_q13 = df.drop(['date', 'lights'], axis=1)

In [37]:
df_q13

Appliances         T1       RH_1         T2       RH_2         T3  \
0              60  19.890000  47.596667  19.200000  44.790000  19.790000   
1              60  19.890000  46.693333  19.200000  44.722500  19.790000   
2              50  19.890000  46.300000  19.200000  44.626667  19.790000   
3              50  19.890000  46.066667  19.200000  44.590000  19.790000   
4              60  19.890000  46.333333  19.200000  44.530000  19.790000   
...           ...        ...        ...        ...        ...        ...   
19730         100  25.566667  46.560000  25.890000  42.025714  27.200000   
19731          90  25.500000  46.500000  25.754000  42.080000  27.133333   
19732         270  25.500000  46.596667  25.628571  42.768571  27.050000   
19733         420  25.500000  46.990000  25.414000  43.036000  26.890000   
19734         430  25.500000  46.600000  25.264286  42.971429  26.823333   

            RH_3         T4       RH_4         T5       RH_5         T6  \
0      44.730000  19.000000  45.566667  17.166667  55.200000   7.026667   
1      44.790000  19.000000  45.992500  17.166667  55.200000   6.833333   
2      44.933333  18.926667  45.890000  17.166667  55.090000   6.560000   
3      45.000000  18.890000  45.723333  17.166667  55.090000   6.433333   
4      45.000000  18.890000  45.530000  17.200000  55.090000   6.366667   
...          ...        ...        ...        ...        ...        ...   
19730  41.163333  24.700000  45.590000  23.200000  52.400000  24.796667   
19731  41.223333  24.700000  45.590000  23.230000  52.326667  24.196667   
19732  41.690000  24.700000  45.730000  23.230000  52.266667  23.626667   
19733  41.290000  24.700000  45.790000  23.200000  52.200000  22.433333   
19734  41.156667  24.700000  45.963333  23.200000  52.200000  21.026667   

            RH_6         T7       RH_7       T8       RH_8         T9  \
0      84.256667  17.200000  41.626667  18.2000  48.900000  17.033333   
1      84.063333  17.200000  41.560000  18.2000  48.863333  17.066667   
2      83.156667  17.200000  41.433333  18.2000  48.730000  17.000000   
3      83.423333  17.133333  41.290000  18.1000  48.590000  17.000000   
4      84.893333  17.200000  41.230000  18.1000  48.590000  17.000000   
...          ...        ...        ...      ...        ...        ...   
19730   1.000000  24.500000  44.500000  24.7000  50.074000  23.200000   
19731   1.000000  24.557143  44.414286  24.7000  49.790000  23.200000   
19732   1.000000  24.540000  44.400000  24.7000  49.660000  23.200000   
19733   1.000000  24.500000  44.295714  24.6625  49.518750  23.200000   
19734   1.000000  24.500000  44.054000  24.7360  49.736000  23.200000   

          RH_9      T_out  Press_mm_hg     RH_out  Windspeed  Visibility  \
0      45.5300   6.600000        733.5  92.000000   7.000000   63.000000   
1      45.5600   6.483333        733.6  92.000000   6.666667   59.166667   
2      45.5000   6.366667        733.7  92.000000   6.333333   55.333333   
3      45.4000   6.250000        733.8  92.000000   6.000000   51.500000   
4      45.4000   6.133333        733.9  92.000000   5.666667   47.666667   
...        ...        ...          ...        ...        ...         ...   
19730  46.7900  22.733333        755.2  55.666667   3.333333   23.666667   
19731  46.7900  22.600000        755.2  56.000000   3.500000   24.500000   
19732  46.7900  22.466667        755.2  56.333333   3.666667   25.333333   
19733  46.8175  22.333333        755.2  56.666667   3.833333   26.166667   
19734  46.8450  22.200000        755.2  57.000000   4.000000   27.000000   

       Tdewpoint        rv1        rv2  
0       5.300000  13.275433  13.275433  
1       5.200000  18.606195  18.606195  
2       5.100000  28.642668  28.642668  
3       5.000000  45.410389  45.410389  
4       4.900000  10.084097  10.084097  
...          ...        ...        ...  
19730  13.333333  43.096812  43.096812  
19731  13.300000  49.282940  49.282940  
19732  13.266667  29.199117  29.19

In [38]:
from sklearn.preprocessing import MinMaxScaler

In [39]:
minmax = MinMaxScaler()

In [40]:
minmax.fit(df_q13)

MinMaxScaler()

In [41]:
df_q13_tran = minmax.transform(df_q13)

In [43]:
df_q13_tran = pd.DataFrame(df_q13_tran,columns=df_q13.columns)

In [44]:
df_q13_tran

Appliances        T1      RH_1        T2      RH_2        T3      RH_3  \
0        0.046729  0.327350  0.566187  0.225345  0.684038  0.215188  0.746066   
1        0.046729  0.327350  0.541326  0.225345  0.682140  0.215188  0.748871   
2        0.037383  0.327350  0.530502  0.225345  0.679445  0.215188  0.755569   
3        0.037383  0.327350  0.524080  0.225345  0.678414  0.215188  0.758685   
4        0.046729  0.327350  0.531419  0.225345  0.676727  0.215188  0.758685   
...           ...       ...       ...       ...       ...       ...       ...   
19730    0.084112  0.926786  0.537657  0.711655  0.606309  0.830841  0.579374   
19731    0.074766  0.919747  0.536006  0.701769  0.607836  0.825302  0.582178   
19732    0.242991  0.919747  0.538666  0.692651  0.627198  0.818378  0.603988   
19733    0.383178  0.919747  0.549491  0.677054  0.634717  0.805085  0.585294   
19734    0.392523  0.919747  0.538758  0.666171  0.632902  0.799546  0.579062   

             T4      RH_4        T5      RH_5        T6      RH_6        T7  \
0      0.351351  0.764262  0.175506  0.381691  0.381070  0.841827  0.170594   
1      0.351351  0.782437  0.175506  0.381691  0.375443  0.839872  0.170594   
2      0.344745  0.778062  0.175506  0.380037  0.367487  0.830704  0.170594   
3      0.341441  0.770949  0.175506  0.380037  0.363800  0.833401  0.164310   
4      0.341441  0.762697  0.178691  0.380037  0.361859  0.848264  0.170594   
...         ...       ...       ...       ...       ...       ...       ...   
19730  0.864865  0.765258  0.752031  0.339590  0.898317  0.000000  0.858624   
19731  0.864865  0.765258  0.754897  0.338487  0.880852  0.000000  0.864010   
19732  0.864865  0.771233  0.754897  0.337585  0.864260  0.000000  0.862394   
19733  0.864865  0.773794  0.752031  0.336583  0.829525  0.000000  0.858624   
19734  0.864865  0.781192  0.752031  0.336583  0.788580  0.000000  0.858624   

           RH_7        T8      RH_8        T9      RH_9     T_out  \
0      0.653428  0.173329  0.661412  0.223032  0.677290  0.372990   
1      0.651064  0.173329  0.660155  0.226500  0.678532  0.369239   
2      0.646572  0.173329  0.655586  0.219563  0.676049  0.365488   
3      0.641489  0.164175  0.650788  0.219563  0.671909  0.361736   
4      0.639362  0.164175  0.650788  0.219563  0.671909  0.357985   
...         ...       ...       ...       ...       ...       ...   
19730  0.755319  0.768386  0.701645  0.864724  0.729443  0.891747   
19731  0.752280  0.768386  0.691912  0.864724  0.729443  0.887460   
19732  0.751773  0.768386  0.687457  0.864724  0.729443  0.883173   
19733  0.748075  0.764953  0.682617  0.864724  0.730581  0.878885   
19734  0.739504  0.771681  0.690062  0.864724  0.731719  0.874598   

       Press_mm_hg    RH_out  Windspeed  Visibility  Tdewpoint       rv1  \
0         0.097674  0.894737   0.500000    0.953846   0.538462  0.265449   
1         0.100000  0.894737   0.476190    0.894872   0.533937  0.372083   
2         0.102326  0.894737   0.452381    0.835897   0.529412  0.572848   
3         0.104651  0.894737   0.428571    0.776923   0.524887  0.908261   
4         0.106977  0.894737   0.404762    0.717949   0.520362  0.201611   
...            ...       ...        ...         ...        ...       ...   
19730     0.602326  0.416667   0.238095    0.348718   0.901961  0.861981   
19731     0.602326  0.421053   0.250000    0.361538   0.900452  0.985726   
19732     0.602326  0.425439   0.261905    0.374359   0.898944  0.583979   
19733     0.602326  0.429825   0.273810    0.387179   0.897436  0.126371   
19734     0.602326  0.434211   0.285714    0.400000   0.895928  0.682391   

            rv2  
0      0.265449  
1      0.372083  
2      0.572848  
3      0.908261  
4      0.201611  
...         ...  
19730  0.861981  
19731  0.985726  
19732  0.583979  
19733  0.126371  
19734  0.682391  

[19735 rows x 27 columns]

In [49]:
x = df_q13_tran.drop('Appliances',axis=1)
y = df_q13_tran['Appliances']

In [50]:
y 

0        0.046729
1        0.046729
2        0.037383
3        0.037383
4        0.046729
           ...   
19730    0.084112
19731    0.074766
19732    0.242991
19733    0.383178
19734    0.392523
Name: Appliances, Length: 19735, dtype: float64

In [51]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [52]:
df_q13_reg = LinearRegression()

In [53]:
df_q13_reg.fit(x_train,y_train)

LinearRegression()

In [54]:
df_q13_prediction = df_q13_reg.predict(x_test)

In [55]:
from sklearn.metrics import mean_absolute_error

In [57]:
mean_absolute_error(y_test,df_q13_prediction)

0.05013362397742957

In [58]:
np.sum(np.square(df_q13_prediction-y_test))

45.34762967266378

In [59]:
from sklearn.metrics import mean_squared_error

In [62]:
import math
math.sqrt(mean_squared_error(df_q13_prediction,y_test))

0.08751444947661711

In [63]:
from sklearn.metrics import r2_score

In [65]:
r2_score(y_test,df_q13_prediction)

0.14890246319303524

In [69]:
df_q13_reg.coef_

array([-0.00328105,  0.5535466 , -0.23617792, -0.45669795,  0.29062714,
        0.09604827,  0.028981  ,  0.02638578, -0.01565684,  0.01600579,
        0.23642491,  0.03804865,  0.01031878, -0.04461364,  0.10199505,
       -0.15759548, -0.18994077, -0.03980032, -0.32185967,  0.00683933,
       -0.07767065,  0.02918313,  0.01230661,  0.11775773,  0.0007701 ,
        0.0007701 ])

In [70]:
x.columns

Index(['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5',
       'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'T_out',
       'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility', 'Tdewpoint', 'rv1',
       'rv2'],
      dtype='object')

In [71]:
from sklearn.linear_model import Ridge

In [72]:
df_q13_ridge = Ridge(alpha = 0.4)

In [73]:
df_q13_ridge.fit(x_train,y_train)

Ridge(alpha=0.4)

In [74]:
df_q13_ridge_pred = df_q13_ridge.predict(x_test)

In [75]:
from sklearn.metrics import mean_squared_error

In [76]:
math.sqrt(mean_squared_error(y_test,df_q13_ridge_pred))

0.08753385704628003

In [77]:
from sklearn.linear_model import Lasso

In [78]:
df_q13_lasso = Lasso(alpha=0.001)

In [79]:
df_q13_lasso.fit(x_train,y_train)

Lasso(alpha=0.001)

In [80]:
df_q13_lasso.coef_

array([ 0.        ,  0.01787993,  0.        , -0.        ,  0.        ,
        0.        , -0.        ,  0.        , -0.        ,  0.        ,
        0.        , -0.        , -0.        , -0.        ,  0.        ,
       -0.00011004, -0.        , -0.        ,  0.        , -0.        ,
       -0.04955749,  0.00291176,  0.        ,  0.        , -0.        ,
       -0.        ])

In [81]:
df_q13_lasso.predict(x_test)

array([0.07370267, 0.08143458, 0.07716072, ..., 0.07792848, 0.09034412,
       0.08359255])

In [82]:
math.sqrt(mean_squared_error(y_test,df_q13_lasso.predict(x_test)))

0.09358170467245137